spring.application.name=coin-price-tracker
spring.main.banner-mode=off

telegram.bot.token=8984573120:AAHNUacQ6wk-dExt-EX1oQz7VpbDQrzJkzE
telegram.chat.id=7672916303

app.coins=BTCUSDT,ETHUSDT,BNBUSDT

app.alert.threshold=0.08